In [1]:
import numpy as np
import pandas as pd

In [2]:

df=pd.read_csv(r"C:\Users\Student\Desktop\country.csv")

In [3]:
df.head()

,0,Data,NaN,2016,NaN.1,NaN.2
0,1,CountryName,CountryCode,Population growth,Total population,Area (sq. km)
1,2,Brazil,BRA,0.82,207652865.00,8358140.00
2,3,Switzerland,CHE,1.08,8372098.00,39516.00
3,4,Germany,DEU,1.19,82667685.00,348900.00
4,5,Denmark,DNK,0.83,?,42262.00

In [4]:
df=pd.read_csv(r"C:\Users\Student\Desktop\country.csv",header=1)

In [5]:
df.head()

   1  CountryName CountryCode Population growth Total population Area (sq. km)
0  2       Brazil         BRA              0.82     207652865.00    8358140.00
1  3  Switzerland         CHE              1.08       8372098.00      39516.00
2  4      Germany         DEU              1.19      82667685.00     348900.00
3  5      Denmark         DNK              0.83                ?      42262.00
4  6        Spain         ESP             -0.01      46443959.00     500210.00

In [6]:
# df.drop("1",axis=1,inplace=True)
# df.drop("CountryCode",axis=1,inplace=True)

In [7]:
df.drop(columns=["1","CountryCode"],inplace=True)

In [8]:
df.head()

   CountryName Population growth Total population Area (sq. km)
0       Brazil              0.82     207652865.00    8358140.00
1  Switzerland              1.08       8372098.00      39516.00
2      Germany              1.19      82667685.00     348900.00
3      Denmark              0.83                ?      42262.00
4        Spain             -0.01      46443959.00     500210.00

In [9]:
df.rename(index=df.CountryName,inplace=True)

In [10]:
df.drop("CountryName",axis=1,inplace=True)

In [11]:
df.head()

            Population growth Total population Area (sq. km)
Brazil                   0.82     207652865.00    8358140.00
Switzerland              1.08       8372098.00      39516.00
Germany                  1.19      82667685.00     348900.00
Denmark                  0.83                ?      42262.00
Spain                   -0.01      46443959.00     500210.00

In [12]:
df.rename(columns={"Population growth":"growth","Total population":"total","Area (sq. km)":"area"},inplace=True)

In [13]:
df

            growth          total          area
Brazil        0.82   207652865.00    8358140.00
Switzerland   1.08     8372098.00      39516.00
Germany       1.19    82667685.00     348900.00
Denmark       0.83              ?      42262.00
Spain        -0.01    46443959.00     500210.00
France        0.41    66896109.00     547557.00
Japan        -0.12   126994511.00     364560.00
Greece       -0.69    10746740.00     128900.00
Iran          1.15    80277428.00    1628760.00
Kuwait        2.92     4052584.00             ?
Morocco          ?    35276786.00     446300.00
Nigeria       2.62   185989640.00     910770.00
Qatar         3.50     2569804.00      11610.00
Sweden           ?     9903122.00     407310.00
India         1.15  1324171354.00    2973190.00
World         1.18  7442135578.00  129733172.70

In [14]:
df.dtypes

growth    object
total     object
area      object
dtype: object

In [15]:
df.describe()

       growth       total       area
count      16          16         16
unique     14          16         16
top      1.15  8372098.00  348900.00
freq        2           1          1

In [16]:
df["growth"]=pd.to_numeric(df["growth"],errors="coerce")
df["total"]=pd.to_numeric(df["total"],errors="coerce")
df["area"]=pd.to_numeric(df["area"],errors="coerce")

In [17]:
df.dtypes

growth    float64
total     float64
area      float64
dtype: object

In [18]:
df.describe()

          growth         total          area
count  14.000000  1.500000e+01  1.500000e+01
mean    1.145000  6.422767e+08  9.762744e+06
std     1.174287  1.909868e+09  3.325701e+07
min    -0.690000  2.569804e+06  1.161000e+04
25%     0.512500  1.032493e+07  2.389000e+05
50%     1.115000  6.689611e+07  4.463000e+05
75%     1.187500  1.564921e+08  1.269765e+06
max     3.500000  7.442136e+09  1.297332e+08

In [19]:
a=np.array([1,"12", "13.5", "mft", 17, 215])
s=pd.Series(a)
s

0       1
1      12
2    13.5
3     mft
4      17
5     215
dtype: object

In [21]:
# pd.to_numeric(s,errors="raise")

In [22]:
pd.to_numeric(s,errors="ignore")

0       1
1      12
2    13.5
3     mft
4      17
5     215
dtype: object

In [23]:
pd.to_numeric(s,errors="coerce")

0      1.0
1     12.0
2     13.5
3      NaN
4     17.0
5    215.0
dtype: float64

In [38]:
np.max(df, axis=0, out=None, keepdims=False)

growth    3.500000e+00
total     7.442136e+09
area      1.297332e+08
dtype: float64

In [39]:
maxpop =df["total"].max()
maxpop

7442135578.0

In [40]:
df["total"][df["total"]==maxpop]

World    7.442136e+09
Name: total, dtype: float64

In [42]:
df.drop("World", axis=0, inplace=True)

In [43]:
df["total"][df["total"]==maxpop]

Series([], Name: total, dtype: float64)

In [46]:
df["total"].min()

2569804.0

In [47]:
from sklearn.impute import SimpleImputer

In [48]:
i=SimpleImputer(missing_values=np.nan, strategy="mean")
i.fit(df)

SimpleImputer()

In [54]:
new=i.transform(df)
new

array([[ 8.20000000e-01,  2.07652865e+08,  8.35814000e+06],
       [ 1.08000000e+00,  8.37209800e+06,  3.95160000e+04],
       [ 1.19000000e+00,  8.26676850e+07,  3.48900000e+05],
       [ 8.30000000e-01,  1.56572478e+08,  4.22620000e+04],
       [-1.00000000e-02,  4.64439590e+07,  5.00210000e+05],
       [ 4.10000000e-01,  6.68961090e+07,  5.47557000e+05],
       [-1.20000000e-01,  1.26994511e+08,  3.64560000e+05],
       [-6.90000000e-01,  1.07467400e+07,  1.28900000e+05],
       [ 1.15000000e+00,  8.02774280e+07,  1.62876000e+06],
       [ 2.92000000e+00,  4.05258400e+06,  1.19342750e+06],
       [ 1.14230769e+00,  3.52767860e+07,  4.46300000e+05],
       [ 2.62000000e+00,  1.85989640e+08,  9.10770000e+05],
       [ 3.50000000e+00,  2.56980400e+06,  1.16100000e+04],
       [ 1.14230769e+00,  9.90312200e+06,  4.07310000e+05],
       [ 1.15000000e+00,  1.32417135e+09,  2.97319000e+06]])

In [55]:
newdf=pd.DataFrame(new,index=df.index, columns=df.columns)
newdf

               growth         total       area
Brazil       0.820000  2.076529e+08  8358140.0
Switzerland  1.080000  8.372098e+06    39516.0
Germany      1.190000  8.266768e+07   348900.0
Denmark      0.830000  1.565725e+08    42262.0
Spain       -0.010000  4.644396e+07   500210.0
France       0.410000  6.689611e+07   547557.0
Japan       -0.120000  1.269945e+08   364560.0
Greece      -0.690000  1.074674e+07   128900.0
Iran         1.150000  8.027743e+07  1628760.0
Kuwait       2.920000  4.052584e+06  1193427.5
Morocco      1.142308  3.527679e+07   446300.0
Nigeria      2.620000  1.859896e+08   910770.0
Qatar        3.500000  2.569804e+06    11610.0
Sweden       1.142308  9.903122e+06   407310.0
India        1.150000  1.324171e+09  2973190.0

In [57]:
df.to_csv(r"dataset_clean.csv")