In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [29]:
df=pd.read_csv(r"C:\Users\Student\Desktop\boston.csv")
df.head()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [30]:
df.drop(["Unnamed: 0"],axis=1,inplace=True)
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [36]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=30)

In [39]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [40]:
y_pred=model.predict(x_test)

In [41]:
model.predict([[0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.6,12.43]])

array([22.87544163])

In [45]:
from sklearn.preprocessing import StandardScaler

In [63]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [64]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=30)
scaler=StandardScaler()
x_train_scale=scaler.fit_transform(x_train)
x_test_scale=scaler.fit_transform(x_test)

model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
sample=[[0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.6,12.43]]
sample_scale=scaler.fit_transform(sample)
model.predict(sample_scale)

array([39.0845885])

In [65]:
mse=mean_squared_error(y_test,y_pred)
mse

17.93304218869928

In [66]:
mae=mean_absolute_error(y_test,y_pred)
mae

3.2254104069763407

In [71]:
r2=r2_score(y_test,y_pred)
r2
#above 70% is good for ml

-25.431032122882524

In [68]:
newx=x[:,[3,5]]
newy=y

In [69]:

x_train,x_test,y_train,y_test=train_test_split(newx,newy,test_size=0.2,random_state=30)
scaler=StandardScaler()
x_train_scale=scaler.fit_transform(x_train)
x_test_scale=scaler.fit_transform(x_test)

model=LinearRegression()
model.fit(x_train_scale,y_train)
y_pred=model.predict(x_test)
sample=[[1,4]]
sample_scale=scaler.fit_transform(sample)
model.predict(sample_scale)

array([22.53762376])

In [72]:
mae=mean_absolute_error(y_test,y_pred)
mae

40.597947927490125

In [73]:
mse=mean_squared_error(y_test,y_pred)
mse

1681.51137156334

In [74]:
r2=r2_score(y_test,y_pred)
r2

-25.431032122882524