In [1]:
import numpy as np
import pandas as pd

In [3]:
data_house=pd.read_csv(r"C:\Users\Student\Desktop\house.csv")
data_house.sample(5)

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
1746,100,2,True,True,True,Central Janatabad,3.600000e+09,120000.00
1570,86,2,True,True,True,Pardis,7.800000e+08,26000.00
3070,105,2,True,True,True,West Ferdows Boulevard,3.500000e+09,116666.67
3197,62,2,False,True,False,Punak,2.300000e+09,76666.67
23,99,2,True,True,True,Moniriyeh,2.277000e+09,75900.00

In [4]:
data_house.dtypes

Area           object
Room            int64
Parking          bool
Warehouse        bool
Elevator         bool
Address        object
Price         float64
Price(USD)    float64
dtype: object

In [5]:
data_house["Area"]=pd.to_numeric(data_house["Area"],errors="coerce")

In [7]:
data_house.replace({True:1,False:0},inplace=True)
data_house.sample(5)

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
2043,88.0,2,1,1,1,Shahrake Qods,1.135200e+09,37840.00
586,140.0,2,1,1,1,Saadat Abad,8.400000e+09,280000.00
196,210.0,3,1,1,1,Pasdaran,1.575000e+10,525000.00
1178,75.0,2,1,1,1,Tarasht,2.150000e+09,71666.67
642,235.0,3,1,1,1,Gheitarieh,2.650000e+10,883333.33

In [8]:
data_house.isnull().sum()

Area           6
Room           0
Parking        0
Warehouse      0
Elevator       0
Address       23
Price          0
Price(USD)     0
dtype: int64

In [9]:
data_house.dropna(subset=["Area","Address"],inplace=True)

In [10]:
data_house.isnull().sum()

Area          0
Room          0
Parking       0
Warehouse     0
Elevator      0
Address       0
Price         0
Price(USD)    0
dtype: int64

In [11]:
data_house.drop_duplicates(inplace=True)

In [12]:
data_house.reset_index(inplace=True,drop=True)

In [15]:
address_map={adre:i for i, adre in enumerate(data_house["Address"].unique(),start=1)}
data_house["number_address"]=data_house["Address"].map(address_map)

In [16]:
data_house.sample(5)

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD),number_address
440,61.0,1,1,1,1,Shahran,1.850000e+09,61666.67,1
2349,73.0,2,1,1,1,Parand,3.850000e+08,12833.33,28
3068,60.0,1,0,0,0,Parand,3.000000e+08,10000.00,28
1686,83.0,2,1,1,1,Jeyhoon,2.200000e+09,73333.33,51
3048,48.0,1,0,0,0,Beryanak,7.400000e+08,24666.67,62