In [23]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [24]:
data_house=pd.read_csv(r"C:\Users\Student\Desktop\house.csv")
data_house.sample(5)

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
2076,76,2,True,True,True,Shahr-e-Ziba,2.850000e+09,95000.00
2390,147,3,True,True,True,Saadat Abad,9.114000e+09,303800.00
1260,90,2,True,True,True,Qazvin Imamzadeh Hassan,1.620000e+09,54000.00
98,128,3,True,True,True,Marzdaran,6.700000e+09,223333.33
3443,70,1,True,True,True,Punak,3.500000e+09,116666.67

In [25]:
data_house.dtypes

Area           object
Room            int64
Parking          bool
Warehouse        bool
Elevator         bool
Address        object
Price         float64
Price(USD)    float64
dtype: object

In [26]:
data_house["Area"]=pd.to_numeric(data_house["Area"],errors="coerce")

In [27]:
data_house.replace({True:1,False:0},inplace=True)
data_house.sample(5)

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
3324,63.0,1,1,1,1,Punak,2.200000e+09,73333.33
1209,127.0,2,1,1,1,Ekhtiarieh,8.890000e+09,296333.33
1294,79.0,2,0,1,0,Northern Janatabad,3.200000e+09,106666.67
661,95.0,2,1,1,1,Punak,4.200000e+09,140000.00
3101,83.0,2,1,1,1,Shahran,2.980000e+09,99333.33

In [28]:
data_house.isnull().sum()

Area           6
Room           0
Parking        0
Warehouse      0
Elevator       0
Address       23
Price          0
Price(USD)     0
dtype: int64

In [29]:
data_house.dropna(subset=["Area","Address"],inplace=True)

In [30]:
data_house.isnull().sum()

Area          0
Room          0
Parking       0
Warehouse     0
Elevator      0
Address       0
Price         0
Price(USD)    0
dtype: int64

In [31]:
data_house.drop_duplicates(inplace=True)

In [32]:
data_house.reset_index(inplace=True,drop=True)

In [33]:
address_map={adre:i for i, adre in enumerate(data_house["Address"].unique(),start=1)}
data_house["Address"]=data_house["Address"].map(address_map)

In [34]:
data_house.sample(5)

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
904,145.0,3,1,1,1,69,1.362500e+10,454166.67
1631,125.0,2,1,1,1,29,6.000000e+09,200000.00
1323,120.0,2,1,1,1,9,7.300000e+09,243333.33
1234,75.0,2,0,1,1,3,6.200000e+08,20666.67
2270,66.0,2,1,1,0,8,2.200000e+09,73333.33

In [35]:
address_avg_price=data_house.groupby("Address").apply(lambda group:group["Price"].sum()/group["Area"].sum())
data_house["Average_mean_price"]=data_house["Address"].map(address_avg_price)
data_house.sample(3)

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD),Average_mean_price
1763,170.0,4,1,1,1,6,3.060000e+09,102000.0,1.764413e+07
1950,57.0,1,1,1,1,42,2.400000e+09,80000.0,3.846429e+07
304,165.0,3,1,1,1,67,1.050000e+10,350000.0,6.742431e+07

In [36]:
data_house.columns

Index(['Area', 'Room', 'Parking', 'Warehouse', 'Elevator', 'Address', 'Price',
       'Price(USD)', 'Average_mean_price'],
      dtype='object')

In [37]:
feature=['Area', 'Room', 'Parking', 'Warehouse', 'Elevator', 'Address']
x=data_house[feature].values
y=data_house["Price"].values

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)

In [40]:
x_train.shape

(2593, 6)

In [41]:
x_test.shape

(649, 6)

In [42]:
from sklearn.linear_model import LinearRegression

In [44]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [46]:
y_pred=reg.predict(x_test)

In [50]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

In [48]:
ridge=Ridge(alpha=0.1)
ridge.fit(x_train,y_train)

Ridge(alpha=0.1)

In [51]:
y_ridge=ridge.predict(x_test)
ridge_mse=mean_squared_error(y_test,y_ridge)
ridge_mse

3.2799628114872644e+19

In [54]:
np.round(ridge_mse,2)

3.2799628114872644e+19

In [56]:
round(reg.score(x_train,y_train),2)

0.57

In [57]:
round(reg.score(x_test,y_test),2)

0.31

In [58]:
ridge_score_train=ridge.score(x_train,y_train)
round(ridge_score_train,2)

0.57

In [59]:
ridge_score_train=ridge.score(x_test,y_test)
round(ridge_score_train,2)

0.31

In [60]:
#lasso ham ejra kardim
#ham lasso ham ridge ro ejra mikonim