In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df=pd.read_csv(r"C:\Users\Student\Desktop\hospital.csv")
df.sample(3)

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
130,54,0,2,160,201,0,1,163,0,0.0,2,1,2,1
33,54,1,2,125,273,0,0,152,0,0.5,0,1,2,1
147,60,0,3,150,240,0,1,171,0,0.9,2,0,2,1

In [3]:
df.dtypes

age           int64
sex           int64
cp            int64
trtbps        int64
chol          int64
fbs           int64
restecg       int64
thalachh      int64
exng          int64
oldpeak     float64
slp           int64
caa           int64
thall         int64
output        int64
dtype: object

In [4]:
df.shape

(303, 14)

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [7]:
df["restecg"].value_counts()

restecg
1    151
0    147
2      4
Name: count, dtype: int64

In [8]:
df=pd.get_dummies(df,columns=['restecg'])
df

,age,sex,cp,trtbps,chol,fbs,thalachh,exng,oldpeak,slp,caa,thall,output,restecg_0,restecg_1,restecg_2
0,63,1,3,145,233,1,150,0,2.3,0,0,1,1,True,False,False
1,37,1,2,130,250,0,187,0,3.5,0,0,2,1,False,True,False
2,41,0,1,130,204,0,172,0,1.4,2,0,2,1,True,False,False
3,56,1,1,120,236,0,178,0,0.8,2,0,2,1,False,True,False
4,57,0,0,120,354,0,163,1,0.6,2,0,2,1,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,123,1,0.2,1,0,3,0,False,True,False
299,45,1,3,110,264,0,132,0,1.2,1,0,3,0,False,True,False
300,68,1,0,144,193,1,141,0,3.4,1,2,3,0,False,True,False
301,57,1,0,130,131,0,115,1,1.2,1,1,3,0,False,True,False
302,57,0,1,130,236,0,174,0,0.0,1,1,2,0,True,False,False

In [9]:
label=[]
for i in df.columns:
    if i!="output":
        label.append(i)
x=np.asarray(df[label])
y=np.asarray(df["output"])

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
s=StandardScaler()
s.fit_transform(x)

array([[ 0.94979429,  0.68265615,  1.97647049, ...,  1.02685041,
        -1.        , -0.11585689],
       [-1.92854796,  0.68265615,  1.005911  , ..., -0.97385168,
         1.        , -0.11585689],
       [-1.48572607, -1.46486632,  0.0353515 , ...,  1.02685041,
        -1.        , -0.11585689],
       ...,
       [ 1.50332164,  0.68265615, -0.93520799, ..., -0.97385168,
         1.        , -0.11585689],
       [ 0.28556146,  0.68265615, -0.93520799, ..., -0.97385168,
         1.        , -0.11585689],
       [ 0.28556146, -1.46486632,  0.0353515 , ...,  1.02685041,
        -1.        , -0.11585689]])

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42,stratify=df["sex"])

In [13]:
scaler=StandardScaler()
x_train_scale=scaler.fit_transform(x_train)
x_test_scale=scaler.transform(x_test)

In [15]:
p_grid={"n_neighbors":np.arange(1,50)}
knn=KNeighborsClassifier()
knn_cv=GridSearchCV(knn,p_grid,cv=5,scoring="accuracy")
knn_cv.fit(x_train_scale,y_train)
print(knn_cv.best_params_)
print(knn_cv.best_score_)

{'n_neighbors': 26}
0.839313399778516

In [16]:
knn=KNeighborsClassifier(n_neighbors=10,metric="minkowski",p=2)
knn.fit(x_train_scale,y_train)
knn.score(x_test_scale,y_test)

0.8461538461538461